[functions.create-checkout]
verify_jwt = false
[functions.order-status]
verify_jwt = false
[functions.stripe-webhook]
verify_jwt = false
[functions.download-original]
verify_jwt = false

[functions.submit-message]
verify_jwt = false
[functions.add-admin-user]
verify_jwt = false

[functions.physical-checkout]
verify_jwt = false
