create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table if not exists public.artworks (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  artist text not null check (char_length(artist) between 1 and 160),
  category text not null check (category in ('Portrait','Fantasy','Landscape','Sci-Fi','Abstract','Dreamscape','NFT')),
  serial_number text not null unique check (serial_number ~ '^[A-Za-z0-9-]{4,40}$'),
  price numeric(10,2) not null check (price > 0),
  preview_url text not null,
  original_path text,
  display_width integer not null default 600 check (display_width between 160 and 1600),
  display_height integer not null default 600 check (display_height between 120 and 1600),
  status text not null default 'draft' check (status in ('draft','published','archived')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null, excerpt text not null, body text not null,
  status text not null default 'draft' check (status in ('draft','published')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(), artwork_id bigint not null references public.artworks(id),
  provider text not null check (provider in ('stripe','paypal')), provider_order_id text unique,
  status text not null default 'pending' check (status in ('pending','paid','failed','refunded')),
  amount numeric(10,2) not null, currency text not null default 'usd', buyer_email text,
  access_token_hash text not null, fulfillment_status text not null default 'pending',
  paid_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.licenses (
  id uuid primary key default gen_random_uuid(), order_id uuid not null unique references public.orders(id) on delete cascade,
  expires_at timestamptz not null, download_count integer not null default 0, download_limit integer not null default 3,
  created_at timestamptz not null default now()
);
create table if not exists public.webhook_events (
  provider text not null, event_id text not null, received_at timestamptz not null default now(),
  primary key (provider,event_id)
);

alter table public.admin_users enable row level security;
alter table public.artworks enable row level security;
alter table public.articles enable row level security;
alter table public.orders enable row level security;
alter table public.licenses enable row level security;
alter table public.webhook_events enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.admin_users where user_id = auth.uid()) $$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create policy "public published artworks" on public.artworks for select using (status = 'published' or public.is_admin());
create policy "admins manage artworks" on public.artworks for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "public published articles" on public.articles for select using (status = 'published' or public.is_admin());
create policy "admins manage articles" on public.articles for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins view own marker" on public.admin_users for select to authenticated using (user_id = auth.uid());
create policy "admins view orders" on public.orders for select to authenticated using (public.is_admin());
create policy "admins update fulfillment" on public.orders for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins view licenses" on public.licenses for select to authenticated using (public.is_admin());

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values
  ('previews','previews',true,10485760,array['image/png','image/jpeg','image/webp']),
  ('originals','originals',false,104857600,array['image/png','image/jpeg','image/webp','application/zip'])
on conflict (id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "public reads previews" on storage.objects for select using (bucket_id='previews');
create policy "admins upload previews" on storage.objects for insert to authenticated with check (bucket_id='previews' and public.is_admin());
create policy "admins manage previews" on storage.objects for update to authenticated using (bucket_id='previews' and public.is_admin());
create policy "admins upload originals" on storage.objects for insert to authenticated with check (bucket_id='originals' and public.is_admin());
create policy "admins manage originals" on storage.objects for all to authenticated using (bucket_id='originals' and public.is_admin()) with check (bucket_id='originals' and public.is_admin());

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create trigger artworks_updated before update on public.artworks for each row execute function public.set_updated_at();
create trigger articles_updated before update on public.articles for each row execute function public.set_updated_at();
create trigger orders_updated before update on public.orders for each row execute function public.set_updated_at();

